WikiSidia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userlogin.urls')),
    path('', include('permohonanSumberDaya.urls')),
    path('', include('fasilitasKesehatan.urls')),
    path('', include('warehouseSatgas.urls')),
    path('', include('pesananSumberDaya.urls')),
    path('', include('kendaraan.urls')),
    path('', include('batchPengiriman.urls')),
    path('', include('lokasi.urls')),
    path('', include('itemSumberDaya.urls')),
    path('', include('stockFaskes.urls')),
]

lokasi/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('Lokasi/', listLokasi, name="lokasi"),
    path('Lokasi/CreateLokasi/', createLokasi, name="createLokasi"),
    path('updateLokasi/<str:id_lokasi>', updateLokasi, name="updateLokasi")

]

userlogin/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, login, profile, registerPengguna, registerPenggunaRole, insert_admin_satgas, insert_supplier, insert_petugas_distribusi, logout, insert_petugas_faskes

urlpatterns = [
    path('', index, name='login'),
    path('Home/', login),
    path('Profile/', profile),
    path('Logout/', logout,  name='logout'),
    path('Register/', registerPengguna),
    path('RegisterRole/', registerPenggunaRole),
    path('insertadmin_satgas/', insert_admin_satgas),
    path('insertsupplier/', insert_supplier),
    path('insertpetugas_distribusi/', insert_petugas_distribusi),
    path('insertpetugas_faskes/', insert_petugas_faskes),

]

userlogin/models.py
from django.db import models

# Create your models here.

userlogin/forms.py
from django import forms

PROVINSI_CHOICE=[
    ('Aceh', 'Aceh'),
	('Sumatra Utara', 'Sumatra Utara'),
	('Sumatra Barat', 'Sumatra Barat'),
	('Riau', 'Riau'),
	('Kepulauan Riau', 'Kepulauan Riau'),
	('Jambi', 'Jambi'),
	('Bengkulu', 'Bengkulu'),
	('Sumatra Selatan', 'Sumatra Selatan'),
	('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'),
    ('Lampung', 'Lampung'),
    ('Banten', 'Banten'),
    ('Jawa Barat', 'Jawa Barat'),
    ('DKI Jakarta', 'DKI Jakarta'),
    ('Jawa Tengah', 'Jawa Tengah'),
    ('DIY Yogyakarta', 'DIY Yogyakarta'),
    ('Jawa Timur', 'Jawa Timur'),
    ('Bali', 'Bali'),
    ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
    ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'),
    ('Kalimantan Barat', 'Kalimantan Barat'),
    ('Kalimantan Selatan', 'Kalimantan Selatan'),
    ('Kalimantan Tengah', 'Kalimantan Tengah'),
    ('Kalimantan Timur', 'Kalimantan Timur'),
    ('Kalimantan Utara', 'Kalimantan Utara'),
    ('Gorontalo', 'Gorontalo'),
    ('Sulawesi Barat', 'Sulawesi Barat'),
    ('Sulawesi Selatan', 'Sulawesi Selatan'),
    ('Sulawesi Tengah', 'Sulawesi Tengah'),
    ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
    ('Sulawesi Utara', 'Sulawesi Utara'),
    ('Maluku', 'Maluku'),
    ('Maluku Utara', 'Maluku Utara'),
    ('Papua Barat', 'Papua Barat'),
    ('Papua', 'Papua'),
]

class LoginForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    password = forms.CharField(label = 'Password', max_length=128, widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'type' : 'password',
        'required' : True,
    }))

class ChoiceRoleForm(forms.Form):
    CHOICES=[
        ('Admin','Admin'),
        ('Supplier','Supplier'),
        ('PetugasDistribusi','PetugasDistribusi'),
        ('PetugasFaskes','PetugasFaskes')]
    Role = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

class AdminSatgasRoleForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    password = forms.CharField(label = 'Password', max_length=128, widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'type' : 'password',
        'required' : True,
    }))
    nama = forms.CharField(label = 'Nama Lengkap', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kel = forms.CharField(label = 'Kelurahan', max_length=30, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kec = forms.CharField(label='Kecamatan', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kabkot = forms.CharField(label='Kabupaten/Kota', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_prov = forms.CharField(label='Provinsi', widget=forms.Select(choices=PROVINSI_CHOICE, attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    no_telepon = forms.CharField(label='No. Telepon', max_length=15, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))

class SupplierRoleForm(forms.Form):
    nama_organisasi = forms.CharField(label = 'Nama Organisasi', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    username = forms.CharField(label='Username', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    password = forms.CharField(label = 'Password', max_length=128, widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'type' : 'password',
        'required' : True,
    }))
    nama = forms.CharField(label = 'Nama Lengkap', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kel = forms.CharField(label = 'Kelurahan', max_length=30, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kec = forms.CharField(label='Kecamatan', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kabkot = forms.CharField(label='Kabupaten/Kota', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_prov = forms.CharField(label='Provinsi', widget=forms.Select(choices=PROVINSI_CHOICE, attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    no_telepon = forms.CharField(label = 'No Telepon', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))

class PetugasDistribusiRoleForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    password = forms.CharField(label = 'Password', max_length=128, widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'type' : 'password',
        'required' : True,
    }))
    nama = forms.CharField(label = 'Nama Lengkap', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kel = forms.CharField(label = 'Kelurahan', max_length=30, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kec = forms.CharField(label='Kecamatan', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kabkot = forms.CharField(label='Kabupaten/Kota', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_prov = forms.CharField(label='Provinsi', widget=forms.Select(choices=PROVINSI_CHOICE, attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    no_telepon = forms.CharField(label = 'No Telepon', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    no_sim = forms.CharField(label = 'No. SIM', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))

class PetugasFaskesRoleForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    password = forms.CharField(label = 'Password', max_length=128, widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'type' : 'password',
        'required' : True,
    }))
    nama = forms.CharField(label = 'Nama Lengkap', max_length=50, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kel = forms.CharField(label = 'Kelurahan', max_length=30, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kec = forms.CharField(label='Kecamatan', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_kabkot = forms.CharField(label='Kabupaten/Kota', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    alamat_prov = forms.CharField(label='Provinsi', widget=forms.Select(choices=PROVINSI_CHOICE, attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))
    no_telepon = forms.CharField(label = 'No Telepon', max_length=20, widget = forms.TextInput(attrs = {
        'class' : 'form-control',
        'type' : 'text',
        'required' : True,
    }))

userlogin/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Wikisidia |
        {% block title %}
        {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- stylesheets -->
	  <!-- <link rel="stylesheet" type="text/css" href="../static/userlogin/css/login.css/"> -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body class="login_back area" style="height: 100vh; font-family: 'Poppins', sans-serif;">
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4A64B8;">
        <a class="navbar-brand" href="/">
        <img src="https://upload.wikimedia.org/wikipedia/commons/d/d1/Mobile-Wikipedia-Logo-modified.png" style="border-radius: 2px; width:30px;">
        <b>Wikisidia</b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse center" id="navbarSupportedContent">
            
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
              </li>
            </ul>
            
            {% if role_admin_satgas == True or role_supplier == True or role_petugas_faskes == True or role_petugas_distribusi == True %}
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/Profile">Profile<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/Logout">Logout<span class="sr-only">(current)</span></a>
              </li>
            </ul>
            {% endif %}
        </div>
        
    </nav>

    {% block content %}
    {% endblock %}
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>

userlogin/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
  <header>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="../static/userlogin/img/wikisidia-header.png" class="d-block w-100"">
            {% for row in hasil %}
            <div class=""
              style="position: absolute;
              top: 0;
              background: rgba(255, 255, 255, 0.75);
              color: #4A64B8;
              width: 100%;
              padding: 20px;">
              <h3>Selamat Datang di <b>WikiSidia</b>, <b>{{row.nama}}!</b></h3>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </header>

    <div class="container justify-content-center">
        <div style="height: 40px;"></div>
        <h2 style="text-align: center;">Menu</h2>
        <div style="height: 40px;"></div>
        <div class="row">
            <div class="col">
                <div class="menu">
                    <div class="row row-cols-1 row-cols-md-3">
                        {% if role_admin_satgas or role_petugas_faskes %}
                        <div class="col mb-4">
                          <div class="card h-100">
                            <div class="container" style="width: 150px;">
                              <br>
                              <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/1556/1556324.png" class="card-img-top">
                              <br>
                            </div>
                            <div class="card-body">
                              <h5 class="card-title" style="text-align: center;">Permohonan Sumber Daya</h5>
                              <a href="/PermohonanSumberDaya" class="btn btn-primary btn-block">Pilih</a>
                            </div>
                          </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_supplier %}
                        <div class="col mb-4">
                          <div class="card h-100">
                            <div class="container" style="width: 150px;">
                              <br>
                              <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/2479/2479736.png" class="card-img-top">
                            </div>
                            <br>
                            <div class="card-body">
                              <h5 class="card-title" style="text-align: center;">Item Sumber Daya</h5>
                              <a href="/ItemSumberDaya" class="btn btn-primary btn-block">Pilih</a>
                            </div>
                          </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_supplier %}
                        <div class="col mb-4">
                          <div class="card h-100">
                            <div class="container" style="width: 150px;">
                              <br>
                              <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/2728/2728577.png" class="card-img-top">
                            </div>
                            <br>
                            <div class="card-body">
                              <h5 class="card-title" style="text-align: center;">Pesanan Sumber Daya</h5>
                              <a href="/pesanan" class="btn btn-primary btn-block">Pilih</a>
                            </div>
                          </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_petugas_distribusi %}
                        <div class="col mb-4">
                            <div class="card h-100">
                              <div class="container" style="width: 150px;">
                                <br>
                                <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/4305/4305318.png" class="card-img-top">
                              </div>
                              <br>
                              <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Kendaraan</h5>
                                <a href="/Kendaraan" class="btn btn-primary btn-block">Pilih</a>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_petugas_distribusi %}
                        <div class="col mb-4">
                            <div class="card h-100">
                              <div class="container" style="width: 150px;">
                                <br>
                                <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/2979/2979648.png" class="card-img-top">
                              </div>
                              <br>
                              <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Batch Pengiriman</h5>
                                <a href="/BatchPengiriman" class="btn btn-primary btn-block">Pilih</a>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas %}
                        <div class="col mb-4">
                            <div class="card h-100">
                              <div class="container" style="width: 150px;">
                                <br>
                                <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/854/854996.png" class="card-img-top">
                              </div>
                              <br>
                              <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Lokasi</h5>
                                <a href="/Lokasi" class="btn btn-primary btn-block">Pilih</a>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_supplier or role_petugas_faskes %}
                        <div class="col mb-4">
                            <div class="card h-100">
                              <div class="container" style="width: 150px;">
                                <br>
                                <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/4097/4097484.png" class="card-img-top">
                              </div>
                              <br>
                              <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Fasilitas Kesehatan</h5>
                                <a href="/Faskes" class="btn btn-primary btn-block">Pilih</a>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if role_admin_satgas or role_supplier %}
                        <div class="col mb-4">
                            <div class="card h-100">
                              <div class="container" style="width: 150px;">
                                <br>
                                <img style="width: 125px; display: block; margin-left: auto; margin-right: auto;" src="https://image.flaticon.com/icons/png/512/2562/2562388.png" class="card-img-top">
                              </div>
                              <br>
                              <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Warehouse Satgas</h5>
                                <a href="/WarehouseSatgas" class="btn btn-primary btn-block">Pilih</a>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                      </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

userlogin/templates/registerPengguna.html
{% extends "base.html" %}
{% block meta %}
{% endblock meta %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
    {% block title %}Sign Up{% endblock title %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
</head>
<body class="login_back area">
  <div class="divider"></div>
      <div class="container-fluid">
        <div class="row mainRow align-items-center justify-content-center">
          <div class="login">
            <div style="height: 40px;"></div>
            <h2 style="text-align: center;">Sign Up</h2>
            <div style="height: 20px;"></div>      
            <br>

            {% if formrole %}
            <div class="container">
              <div class="row">
                <form method="POST" action="/RegisterRole/" >
                    {% csrf_token %}
                    <div class="loginForm">
                      <div style="height: 40px;"></div>
                      <h4 style="text-align: center;">Pilih Role</h4>
                      <div style="height: 40px;"></div>
                        <ul class="row justify-content-between" id="id_Role">
                          <div class="col mb-4">
                            <div class="card" style="width: 200px;">
                              <div class="card-body">
                                <img src="https://image.flaticon.com/icons/png/512/2416/2416666.png" class="card-img" alt="admin">
                              </div>
                              <div class="card-footer">
                                <h5><input type="radio" name="Role" value="admin_satgas" required="" id="id_Role_0"> Admin Satgas </h5><br>
                              </div>
                            </div>
                          </div>
                          <div class="col mb-4">
                            <div class="card" style="width: 200px;">
                              <div class="card-body">
                                <img src="https://image.flaticon.com/icons/png/512/2166/2166907.png" class="card-img-top" alt="supplier">
                              </div>
                              <div class="card-footer">
                                <h5><input type="radio" name="Role" value="supplier" required="" id="id_Role_1"> Supplier </h5><br>
                              </div>
                            </div>
                          </div>
                          <div class="col mb-4">
                            <div class="card" style="width: 200px;">
                              <div class="card-body">
                                <img src="https://image.flaticon.com/icons/png/512/2103/2103848.png" class="card-img-top" alt="petugas_distribusi">
                              </div>
                              <div class="card-footer">
                                <h5><input type="radio" name="Role" value="petugas_distribusi" required="" id="id_Role_2"> Petugas Distribusi</h5>
                              </div>
                            </div>
                          </div>
                          <div class="col mb-4">
                            <div class="card" style="width: 200px;">
                              <div class="card-body">
                                <img src="https://image.flaticon.com/icons/png/512/3461/3461720.png" class="card-img-top" alt="admin">
                              </div>
                              <div class="card-footer">
                                <h5><input type="radio" name="Role" value="petugas_faskes" required="" id="id_Role_3"> Petugas Faskes</h5>
                              </div>
                            </div>
                          </div>
                        </ul>
                    </div>
                    <br>
                    <div style="text-align: center;">
                      <input class="btn btn-primary btn-lg" type="submit" value="Register" name="tombol">
                    </div> 
                    <br><br>
                    <p class="text-center">Already have an account? <a href="/">Sign in now!</a></p>
                </form>
                {% endif %}
              </div>
            </div>
            
          <div class="container">
            
              {% if role_admin_satgas %}
              <form method="POST" action="/insertadmin_satgas/">
                {% csrf_token %}
                  <div class="loginForm">
                    <div class="card" style="width: 500px; margin-left: auto;margin-right: auto;">
                      <div class="card-body">
                        {{form.as_table}}
                        <br><br>
                        <input type="submit" value="Register" name="tombol" class="btn btn-primary btn-block">
                        <br>
                        <p class="text-center">Already have an account? <a href="/">Sign in now!</a></p>
                      </div>
                    </div>
                    <br>
                  </div>
              </form>    
              {% endif %}
              
              {% if role_petugas_distribusi %}
              <form method="POST" action="/insertpetugas_distribusi/" >
                {% csrf_token %}
                <div class="loginForm">
                  <div class="card" style="width: 500px; margin-left: auto;margin-right: auto;">
                    <div class="card-body">
                      {{form.as_table}}
                      <br><br>
                      <input type="submit" value="Register" name="tombol" class="btn btn-primary btn-block">
                      <br>
                      <p class="text-center">Already have an account? <a href="/">Sign in now!</a></p>
                    </div>
                  </div>
                  <br>
                </div>
              </form>    
              {% endif %}

              {% if role_petugas_faskes %}
              <form method="POST" action="/insertpetugas_faskes/" >
                {% csrf_token %}
                <div class="loginForm">
                  <div class="card" style="width: 500px; margin-left: auto;margin-right: auto;">
                    <div class="card-body">
                      {{form.as_table}}
                      <br><br>
                      <input type="submit" value="Register" name="tombol" class="btn btn-primary btn-block">
                      <br>
                      <p class="text-center">Already have an account? <a href="/">Sign in now!</a></p>
                    </div>
                  </div>
                  <br>
                </div>
              </form>    
              {% endif %}

              {% if role_supplier %}
              <form method="POST" action="/insertsupplier/" >
                {% csrf_token %}
                <div class="loginForm">
                  <div class="card" style="width: 500px; margin-left: auto;margin-right: auto;">
                    <div class="card-body">
                      {{form.as_table}}
                      <br><br>
                      <input type="submit" value="Register" name="tombol" class="btn btn-primary btn-block">
                      <br>
                      <p class="text-center">Already have an account? <a href="/">Sign in now!</a></p>
                    </div>
                  </div>
                  <br>
                </div>
              </form>   
              {% endif %}
          </div>
        
        </div>
        <p class="text-center" style="color: white;background-color: grey;border-radius: 7px;">{{message}}</p>
      </div>
    </div>
    <div class="divider"></div>


</body>
{% endblock %}
</html>